// Real posts from virgoC0der.github.io content/
window.POSTS = [
  {
    slug: "go-multilingual-localization",
    title: "Go 项目的多语言国际化实战",
    title_en: "Multilingual i18n in Go, the full playbook",
    description: "从 go-i18n 到自研方案，完整拆解 Go 服务端如何优雅支持多语言。",
    date: "2025-04-12",
    readTime: 18,
    tags: ["Go", "i18n", "Backend"],
    category: "Technical",
    color: "var(--yellow)",
    cover: "terminal",
    pinned: true,
  },
  {
    slug: "go-mcp-claude",
    title: "使用 Go 开发 MCP 并接入 Claude Desktop",
    title_en: "Building MCP servers in Go for Claude Desktop",
    description: "用 go-mcp 库把本地 macOS 应用交给 Claude 调度，HTTP + stdio 双模式实战。",
    date: "2025-04-08",
    readTime: 15,
    tags: ["Go", "Claude", "MCP", "AI"],
    category: "AI",
    color: "var(--lavender)",
    cover: "mcp",
    pinned: true,
  },
  {
    slug: "go-i18n-localization",
    title: "Go i18n 本地化深潜",
    title_en: "Deep dive into Go i18n localization",
    description: "CLDR、复数规则、ICU MessageFormat、模板继承，一次讲透。",
    date: "2025-04-05",
    readTime: 20,
    tags: ["Go", "i18n"],
    category: "Technical",
    color: "var(--mint)",
    cover: "globe",
  },
  {
    slug: "golang-docker",
    title: "给 Go 服务打一个 12MB 的 Docker 镜像",
    title_en: "Shrinking Go images to 12MB with multi-stage builds",
    description: "multi-stage build + distroless + upx，一步步压到极限。",
    date: "2025-04-02",
    readTime: 12,
    tags: ["Go", "Docker", "DevOps"],
    category: "DevOps",
    color: "var(--coral-soft)",
    cover: "docker",
  },
  {
    slug: "golang-beginner-guide",
    title: "Go 语言入门指南：从零开始的编程之旅",
    title_en: "Golang from zero: a beginner's roadmap",
    description: "goroutine、channel、interface、module — 一篇带你上路。",
    date: "2025-03-31",
    readTime: 22,
    tags: ["Go", "Programming", "Backend"],
    category: "Tutorial",
    color: "var(--peach)",
    cover: "gopher",
  },
  {
    slug: "claude-mcp-blog-automation",
    title: "Claude + MCP 一键生成博客",
    title_en: "Zero-click blog publishing with Claude + MCP",
    description: "写作、提交、部署、验证，全程交给 AI。",
    date: "2025-03-31",
    readTime: 8,
    tags: ["AI", "Claude", "MCP", "自动化"],
    category: "AI",
    color: "var(--pink)",
    cover: "automation",
  },
  {
    slug: "first",
    title: "在 Mac Mini 上部署私有化大语言模型",
    title_en: "Local LLM on a Mac Mini with Ollama + Open WebUI",
    description: "家用机也能跑 llama3 — 一份极简部署笔记。",
    date: "2025-03-24",
    readTime: 6,
    tags: ["AI Deployment", "Ollama", "Open WebUI"],
    category: "Tutorial",
    color: "var(--lime)",
    cover: "llm",
  },
];

window.TAGS = [
  { name: "Go", count: 5, color: "var(--yellow)" },
  { name: "AI", count: 3, color: "var(--lavender)" },
  { name: "MCP", count: 2, color: "var(--mint)" },
  { name: "Claude", count: 2, color: "var(--pink)" },
  { name: "Backend", count: 2, color: "var(--coral-soft)" },
  { name: "Docker", count: 1, color: "var(--peach)" },
  { name: "DevOps", count: 1, color: "var(--lime)" },
  { name: "i18n", count: 2, color: "var(--yellow-soft)" },
  { name: "Tutorial", count: 3, color: "var(--coral)" },
  { name: "Programming", count: 1, color: "var(--lavender)" },
  { name: "Ollama", count: 1, color: "var(--mint)" },
  { name: "自动化", count: 1, color: "var(--pink)" },
];

window.CATEGORIES = [
  { name: "Technical", count: 2, icon: "⚡" },
  { name: "Tutorial", count: 3, icon: "📘" },
  { name: "AI", count: 2, icon: "🤖" },
  { name: "DevOps", count: 1, icon: "🐳" },
];

window.STACK = [
  { name: "Go", color: "#00ADD8", glyph: "Go" },
  { name: "Python", color: "#3776AB", glyph: "Py" },
  { name: "Swift", color: "#FA7343", glyph: "Sw" },
  { name: "React", color: "#61DAFB", glyph: "Re" },
  { name: "PostgreSQL", color: "#336791", glyph: "Pg" },
  { name: "MongoDB", color: "#47A248", glyph: "Mo" },
  { name: "Redis", color: "#DC382D", glyph: "Rd" },
  { name: "Spanner", color: "#4285F4", glyph: "Sp" },
  { name: "Docker", color: "#2496ED", glyph: "Dk" },
  { name: "Kubernetes", color: "#326CE5", glyph: "K8" },
  { name: "GCP", color: "#4285F4", glyph: "GC" },
  { name: "AWS", color: "#FF9900", glyph: "AW" },
];

window.NOW_ITEMS = [
  { label: "正在写", text: "Go i18n 深度系列第 3 篇", tag: "writing" },
  { label: "正在读", text: "《Designing Data-Intensive Applications》", tag: "reading" },
  { label: "正在做", text: "go-mcp v0.3 — 加入 resource templates", tag: "building" },
  { label: "正在玩", text: "Claude Code + Feishu bot 自动化工作流", tag: "exploring" },
];
